[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "SAP Configurator Messaging Extension"
description = "Handles selections with bi-directional messaging."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# Path (relative to the root) of changelog
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "example", "messaging"]

# Icon to show in the extension manager
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"


# Extension specific dependencies
[dependencies]
"omni.kit.livestream.messaging" = {}
"omni.kit.viewport.utility" = {}
"omni.kit.manipulator.camera" = {}
"omni.kit.window.cursor" = {}
"omni.kit.raycast.query" = {}
"omni.kit.notification_manager" = {optional = true}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "sap.configurator.viewer.messaging"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
]
